sudo: required
services:
  - docker

before_install:
  - docker build -t narcisneacsu194/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run narcisneacsu194/react-test npm test -- --coverage

after_success:
  - docker build -t narcisneacsu194/multi-client ./client
  - docker build -t narcisneacsu194/multi-nginx ./nginx
  - docker build -t narcisneacsu194/multi-server ./server
  - docker build -t narcisneacsu194/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push narcisneacsu194/multi-client
  - docker push narcisneacsu194/multi-nginx
  - docker push narcisneacsu194/multi-server
  - docker push narcisneacsu194/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-337976026627
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
